#!/usr/bin/env node

"use strict";

var c = require('skilstak-colors')

function printMulti(name) {
  console.log(c.multi(name));
}

var printColors = function (name) {
  while (true) {
  console.log(c.r + name + c.x);
  console.log(c.y + name + c.x);
  console.log(c.b + name + c.x);
}}

var printAwesome = function (name) {
  console.log(c.o + name);
}

var coolArg = process.argv[2];

//printMulti(coolArg);
printColors(coolArg);
//printAwesome("SenseiFuzzyBuns, Nickipoo, Sully, Bo, WyWy, MalPal123, and JohnBohn21 are awesome!!!");
