#!/usr/bin/env python3

"My super duper awesome hello world program"

def print_plain(message="hello world"):
    """prints < message > in plain"""
    print(message)


if __name__ == "__main__":
    print_plain("Mr.TommyPants")
